import type { AnalyzeRepositoryResponse } from "../../types/report";

import ArchitectureCard from "./ArchitectureCard";
import CodeQualityCard from "./CodeQualityCard";
import FolderStructureCard from "./FolderStructureCard";
import ImprovementCard from "./ImprovementCard";
import InterviewQuestionsCard from "./InterviewQuestionsCard";
import MarkdownDownload from "./MarkdownDownload";
import ReportGrid from "./ReportGrid";
import ResumeFeedbackCard from "./ResumeFeedbackCard";
import StrengthsCard from "./StrengthsCard";
import SummaryCard from "./SummaryCard";
import TechnologyStackCard from "./TechnologyStackCard";
import WeaknessesCard from "./WeaknessesCard";

interface Props {
  result: AnalyzeRepositoryResponse;
}

export default function ReportViewer({
  result,
}: Props) {
  const { report, markdown } = result;

  return (
    <div className="space-y-10">

      <div className="flex items-center justify-between">

        <div>

          <h2 className="text-3xl font-bold">
            Engineering Review
          </h2>

          <p className="mt-2 text-slate-500">
            Generated by AI Project Reviewer
          </p>

        </div>

        <MarkdownDownload
          markdown={markdown}
        />

      </div>

      <ReportGrid>
        <SummaryCard report={report} />
        <TechnologyStackCard report={report} />
      </ReportGrid>

      <ReportGrid>
        <ArchitectureCard report={report} />
        <FolderStructureCard report={report} />
      </ReportGrid>

      <ReportGrid>
        <CodeQualityCard report={report} />
        <ResumeFeedbackCard report={report} />
      </ReportGrid>

      <ReportGrid>
        <StrengthsCard report={report} />
        <WeaknessesCard report={report} />
      </ReportGrid>

      <div className="space-y-6">

        <h2 className="text-2xl font-bold">
          Recommended Improvements
        </h2>

        {report.improvements.map(
          (item) => (
            <ImprovementCard
              key={item.title}
              {...item}
            />
          ),
        )}

      </div>

      <InterviewQuestionsCard
        report={report}
      />

    </div>
  );
}